### ISSUE TITLE
xcolor not ready to provide \mathcolor

### ISSUE THREAD

**Issue by FrankMittelbach** [latex3/xcolor#16]
Using latex-dev you need to load both color and xcolor to get `\mathcolor`.

```
\documentclass{article}

\usepackage{xcolor}

\begin{document}

$ a \mathcolor{red}{+} b $

\end{document}
```

**Comment by FrankMittelbach** [comment]
so it is and for quite some time ... @davidcarlisle could you please verify and approve (or not)?

**Comment by davidcarlisle** [comment]
@FrankMittelbach  @u-fischer I merged, I think the hesitation of doing a release  at the time was that (unless we do a latex-dev release of xcolor) this will add mathcolor to latex, not just latex-dev as xcolor will input the mathcolor file from the fallback "try the whole tree" search. 

```
$ pdflatex '\RequirePackage{xcolor}\show\mathcolor'
This is pdfTeX, Version 3.141592653-2.6-1.40.24 (TeX Live 2022) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
LaTeX2e <2021-11-15> patch level 1
L3 programming layer <2022-04-10>
(/home/davidc/texmf/tex/latex/xcolor/xcolor.sty
(/usr/local/texlive/2022/texmf-dist/tex/latex/graphics-cfg/color.cfg)
(/usr/local/texlive/2022/texmf-dist/tex/latex/graphics-def/pdftex.def)
(/usr/local/texlive/2022/texmf-dist/tex/latex-dev/graphics/mathcolor.ltx))
> \mathcolor=\protected macro:
```

**Comment by FrankMittelbach** [comment]
ok so if we push that, then \mathcolor becomes available a bit earlier (in case xcolor gets loaded). I think we can live with that *now*. It was a bit different before TL22.
