### ISSUE TITLE
\normalcolor is made fragile again

### ISSUE THREAD

**Issue by FrankMittelbach** [latex3/xcolor#17]
As a result it breaks in places such as
```
\DeclareEmphSequence{\itshape,\emforce\color{blue},\bfseries,\color{black}\scshape}
```
Not unlikely that some other document commands would also need to be `\protected`

**Comment by u-fischer** [comment]
I have uploaded a new version which makes all commands that are `\protected` in color.sty also `\protected` in xcolor.
