### ISSUE TITLE
Do not swallow unknown options

### ISSUE THREAD

**Issue by mrpiggi** [latex3/xcolor#2]
Since package `xcolor` is used by many other packages that commonly pass several options to it, it might be sensible to report unfamiliar options as a warning and not as an easily overlooked info.

https://github.com/latex3/xcolor/blob/a24ee00a71316e382a2c198580c35bb7835ffc5b/xcolor.dtx#L4092-L4093

**Comment by u-fischer** [comment]
Starting with version 3.00  xcolor behaves like (most) other packages and errors with unknown options:

~~~~
\documentclass{article}
\usepackage[blub]{xcolor}
\begin{document}
blub
\end{document}
~~~~

~~~~
! LaTeX Error: Unknown option 'blub' for package xcolor.
~~~~
