### ISSUE TITLE
Retirement of package option `fixpdftex`

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/xcolor#20]
Currently package option `fixpdftex` is provided to load [`pdfcolmk`](https://ctan.org/pkg/pdfcolmk) package to emulate color stack. Since color stack is supported by pdftex since v1.40.0, released in 2007, `fixpdftex` can be changed to do nothing but perhaps throw a warning, and its doc can be adapted.
https://github.com/latex3/xcolor/blob/849682246582946835d28c8f9b2081ff2c340e09/xcolor.dtx#L4019-L4022

**Comment by u-fischer** [comment]
Well it actually does nothing at all, as pdfcolmk does nothing at all (it is only a stubs package since quite some time). But you are right, it is therefore quite unnecessary to even try to load the package. I will adjust that.

**Comment by muzimuzhi** [comment]
Thanks. Feel free to close this issue if it's the time.

**Comment by u-fischer** [comment]
fixed in 3.00
