### ISSUE TITLE
`\current@color` is independent of the target color model

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/xcolor#21]
Or in other words: Should `\selectcolormodel` update `\current@color` and `\default@color`?

For example, with pdftex and pdf mode on, `\current@color` is initialized to gray scale black `0 g 0 G`, and `\default@color` is let to `\current@color` at beginning of document. Then a user writing `\usepackage[cmyk]{xcolor}` may expect that every color in the resulting pdf is represented in cmyk.

But since `\normalcolor`, which does `\let\current@color\default@color` then pushes `\current@color` to color stack, is used by latex2e kernel in several places, `0 g 0 G` will be found multiple times in pdf. Also to machine, `\normalcolor text` will be different to `\color{.} text`.

```tex
\documentclass{article}
\usepackage{xcolor}
\def\showCurrentColor{%
  \setbox0=\hbox{{\normalcolor n}\textcolor{.}{N}}\showbox0 }
\showboxdepth=100
\showboxbreadth=100

\begin{document}
% \selectcolormodel{natural} % default color model
\showCurrentColor

\selectcolormodel{rgb}
\showCurrentColor

\selectcolormodel{cmyk}
\showCurrentColor
\end{document}
```
The `\showbox` part of `{\normalcolor n}` is independent of the target color model, 
```tex
.\pdfcolorstack 0 push {0 g 0 G}
.\OT1/cmr/m/n/10 n
.\pdfcolorstack 0 pop
```
while the part of `\textcolor{.}{N}` is dependent of the target color model.
```tex
% color model = natural
.\pdfcolorstack 0 push {0 g 0 G}
.\OT1/cmr/m/n/10 N
.\pdfcolorstack 0 pop
% color model = rgb
.\pdfcolorstack 0 push {0 0 0 rg 0 0 0 RG}
.\OT1/cmr/m/n/10 N
.\pdfcolorstack 0 pop
% color model = cmyk
.\pdfcolorstack 0 push {0 0 0 1 k 0 0 0 1 K}
.\OT1/cmr/m/n/10 N
.\pdfcolorstack 0 pop
```

**Comment by u-fischer** [comment]
I'm not sure if I would dare to change that. It would affect every document which sets a color model and I don't want to get angry comments that I just broke various test suites for something that seems not to harm anyone. Imho if someone wants to change \normalcolor is should be done explicitly.

**Comment by muzimuzhi** [comment]
> It would affect every document which sets a color model and I don't want to get angry comments that I just broke various test suites for something that seems not to harm anyone.

Perhaps through a new package option?

I admit the gains from this feature are small. Even `xcolor` supports this, other packages may still use a hard-coded default color, for example `tikz`. And as a last resort, one can always use `ghostscript` to convert all colors in a PDF to a specific model.

**Comment by u-fischer** [comment]
I'm not aware of any standard or use case that would force to drop the gray model, even if a document wants to force cmyk or uses spotcolors. So unless some concrete example comes up I don't see a gain here.
