### ISSUE TITLE
Adding an options hook

### ISSUE THREAD

**Issue by AndrewMathas** [latex3/xcolor#29]
A quick search through [tex.stackexchange.com ](https://tex.stackexchange.com/search?q=xcolor+option+clash) reveals a large number of posts about option clashes when using `xcolor`. Many of these are caused by packages loading xcolor with different options. If `xcolor` provided a command for changing these options then most of these problems would disappear.

Not all of the `xcolor` options can be changed mid document but many of them can.

**Comment by u-fischer** [comment]
I have uploaded a new version 3.00 which uses the new LaTeX options handler. With a current LaTeX this will avoid option clash errors. Options can now be used also in a second \usepackage command if it  makes sense, and it is also possible to set some options in the preamble directly. As an example

~~~~
\documentclass{article}
\usepackage{xcolor}
\usepackage[monochrome,table]{xcolor}
\SetKeys[xcolor]{dvipsnames}
\begin{document}
\color{RedOrange} xxxx
\end{document}
~~~~

* This will ignore the `monochrome` option with a warning:
~~~~
LaTeX Warning: Package "xcolor" has already been loaded: ignoring load-time option "monochrome".
~~~~
* It will load colortbl (through the `table` option)
* It will load dvipsnam.de (through the `\SetKeys`).

**Comment by chrislandis** [comment]
Yes, thank you for the quick fix.  I was just starting to look into an "xcolor" option error that started last week on a university-specific document class that I help maintain.  The `newtxtext` package just started loading `xcolor` and I had been loading it subsequently with the `table` option.  Your update here fixes this issue for me.  Thank you!

**Comment by u-fischer** [comment]
Well it wasn't really quick, the code was sitting there since a year, the issue only pushed me to finally sent it to ctan. ;-)

**Comment by ttsc** [comment]
![image](https://github.com/user-attachments/assets/bee3f9c5-9027-4efe-b280-b33421697c5d)

The above part of the documentation appears to be outdated now that this issue has been fixed.
