### ISSUE TITLE
Problems after 3.0 update

### ISSUE THREAD

**Issue by jotagah** [latex3/xcolor#31]
I have an issue after the last xcolor 3 update with pdflatex. I used a lot of packages, some of them load xcolor.

Until the new update my files "compiled" ok, but after yesterday update I got some an error like ! LaTeX Error: Unknown option 'usenames' for package xcolor.

I tried to use \PassOptionsToPackage{usenames,dvipsnames}{xcolor} or \PassOptionsToPackage{usenames}{xcolor}
without success.

I restored the 2.14 and all works fine again.

JH

**Comment by FrankMittelbach** [comment]
It is always helpful if you provide a minimal example that shows the problem, not just a description

**Comment by u-fischer** [comment]
The option usenames is obsolete. But I will change it, so that it issues only a warning not an error.

**Comment by u-fischer** [comment]
I uploaded a version to ctan which will only warn. But try to remove the option, according the changelog it is unneeded since 2004.

**Comment by jotagah** [comment]
Sorry my fault about MWE. I will test the new 3.01 release and will post here any issue, but I do not load xcolor myself. That's my main problem.

**Comment by jotagah** [comment]
I tested your new 3.01 release and confirm that the problem is over. Thanks.

**Comment by mrpiggi** [comment]
@u-fischer I just wanted to draw your attention to a possible typo, in case you haven't noticed it yet: 
https://github.com/latex3/xcolor/commit/c74a17bfb178092afb3bd2bcdfbd0ddf474f2221#r132642683

**Comment by mrpiggi** [comment]
Certainly not. I just didn't spot the fix here on GitHub, at least not in the `main` branch.
