### ISSUE TITLE
option to disable all colors at once

### ISSUE THREAD

**Issue by lalitaalaalitah** [latex3/xcolor#33]
Hi,
I'm extensively using xcolor package to color different commands in my LaTeX. But, if I've to give this book to publisher, I'll like to change all colors to black again. It can be done manually, but, if there is an option to change all colors to black at once, it will be nice.

**Comment by muzimuzhi** [comment]
`monochrome` package option?

**Comment by lalitaalaalitah** [comment]
Thanks. It is solved.
