### ISSUE TITLE
use monochrome option while preserving watermark

### ISSUE THREAD

**Issue by lalitaalaalitah** [latex3/xcolor#34]
Hi,
I'm extensively using xcolor package to color different commands in my LaTeX. To disable all color and make them black, I'm using the option `monochrome`.  Although it solves my problem of replacing many color with black, but it also destroys my Watermark which loses all customization and make it dark black. I'm unable to increase opacity and color of watermark.
Is there any way to avoid applying the `monochrome` option to the watermark which is provided by the package `draftwatermark`.

**Comment by u-fischer** [comment]
This here an issue tracker, not a support forum. Please ask such questions on some Q&A site, e.g. on tex.sx. And don't forget a minimal example. (The monochrome option disables the color commands completely, so you would have to set the watermark color in some other way, e.g. with l3color commands).
